# Generated by Django 5.0.1 on 2024-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('name', 'user')},
        ),
    ]
